[package]
name = "forge"
version = "0.1.0"
edition = "2024"

[dependencies]
colored = "3.0.0"
serde = "1.0.228"
serde_derive = "1.0.228"
serde_yaml = "0.9.34"
tokio = { version = "1.48.0", features = ["full"] }
